config/routes.rb
Rails.application.routes.draw do

  root 'groups#index'

  get 'login', to: 'splash#index'

  devise_for :users

  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  resources :groups, only:[:index, :create, :new] do
    resources :entities, only:[:index, :new, :create, :index]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :categories, dependent: :destroy
  has_many :groups, through: :categories

  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :categories, dependent: :destroy
  has_many :entities, through: :categories, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def authenticate_user!
    return super if user_signed_in? || devise_controller?

    redirect_to(login_path)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @title = 'TRANSACTIONS'
    @group = Group.find(params[:group_id])
    @entities = @group.entities.order(created_at: :desc)
    @amount = @entities.sum(:amount)
  end

  def new
    @title = 'ADD TRANSACTION'
    if Group.where(user: current_user).ids.empty?
      redirect_to(
        new_group_path,
        notice: 'Please create a category first'
      ) and return
    end

    @entity = Entity.new
    group_id = params[:group_id]
    render(:new, locals: { group_id:, my_groups: helpers.check_groups(group_id) })
  end

  def create
    c_ids = params.require(:entity).fetch(:group_ids, [])[1..]
    c_ids << params[:group_id]

    @entity = Entity.new(create_params)

    if @entity.save
      @entity.groups.push(*Group.where(id: c_ids))
      redirect_to(
        group_entities_path(params[:group_id]), notice: 'Transaction created successfully!'
      )
    else
      error_render(@entity.errors.objects.first.full_message)
    end
  end

  private

  def create_params
    params
      .require(:entity)
      .permit(:name, :amount)
      .merge(user: current_user)
  end

  def transaction_params
    params.permit(:group_id).merge(entity: @entity)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @title = 'CATEGORIES'
    @groups = Group
      .select('groups.*, SUM(E.amount) as amount')
      .joins('LEFT JOIN categories as C ON C.group_id = groups.id')
      .joins('LEFT JOIN entities as E ON E.id = C.entity_id')
      .where(user_id: current_user.id)
      .group(:id)
  end

  def new
    @title = 'NEW CATEGORY'
    @group = Group.new
  end

  def create
    @group = Group.new(create_params)
    if @group.save
      redirect_to(root_path, notice: 'Category created successfully')
    else
      render(:new, status: :unprocessable_entity, alert: @group.errors.objects.first.full_message)
    end
  end

  private

  def create_params
    params
      .require(:group)
      .permit(:name, :icon)
      .merge(user: current_user)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @title = 'REGISTER'
    return redirect_to(root_path) if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
  def check_groups(group_id)
    Group.where('user_id = ? AND id <> ?', current_user.id, group_id)
  end

  def format(entity)
    entity.created_at.strftime('%m-%d-%Y')
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def created_by
    render(inline: "Creator: <strong>#{current_user.name}</strong>")
  end

  def total_amount(model)
    render(inline: "Total amount: <strong><i>$</i>#{model.amount || 0}</strong>")
  end

  def check_icon(icon)
    icon.strip == '' ? 'icon.png' : icon
  end
end

app/views/entities/index.html.erb
<section>
  <h4 class="categ-item ft-item">
    <span><%= image_tag(check_icon(@group.icon)) %></span>
    <span><%= @group.name %></span>
  </h4>

  <% if @entities.empty? %>
    <h3>This category has no transactions yet</h3>
  <% else %>
    <ul>
      <% @entities.each do |e| %>
        <li class="trans-item ft-item">
          <h4 class="flex-between">
            <span><%= e.name %></span>
            <strong><i>$</i><%= e.amount %></strong>
          </h4>
          <p><%= format(e) %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <h4><i>TOTAL SPENT: $</i><%= @amount || 0 %></h4>
</section>

<%= link_to('New Transaction', new_group_entity_path) %>

app/views/entities/new.html.erb
<section>
  <%= form_with(model: @entity, url: group_entities_path(group_id)) do |f| %>
    <%= f.text_field(:name, placeholder: 'name', required: true, class:'field') %>

    <%= f.number_field(:amount, placeholder: 'amount', required: true, class:'field') %>

    <div>
      <%= f.label('Select another category') %>
      <%= f.collection_check_boxes(:group_ids, my_groups, :id, :name, class:'field') do |c| %>
        <div>
          <%= c.check_box %>
          <%= c.label %>
        </div>
      <% end %>
    </div>

    <div>
      <%= f.submit "Save", class:'new-ft-btn field' %>
    </div>
  <% end %>
</section>

app/views/groups/index.html.erb
<section>
  <% if @groups.empty? %>
    <h3>Add a new ctegory first</h3>
  <% else %>
    <ul class="flex-col" id="catego_list">
      <% @groups.each do |g| %>
        <li class="categ-item ft-item">
            <%= image_tag(check_icon(g.icon)) %>
          <div>
            <%= link_to(g.name, group_entities_path(g)) %>
            <div class="flex-between">
            <span><%= created_by %></span>
            <span><%= total_amount(g) %></span>
          </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</section>

<%= link_to('New Category', new_group_path, class: 'new-ft-btn') %>

app/views/groups/new.html.erb
<section>
  <%= form_with(model: @group) do |f| %>
    <div>
      <%= f.text_field(:name, placeholder: 'Name', required: true, class:'field') %>
    </div>

    <div>
      <%= f.text_field(:icon, placeholder: 'Icon', required: true, class:'field') %>
    </div>

    <div>
      <%= f.submit "Save", class: 'new-ft-btn field' %>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BigSpender</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.2.0/css/all.css">
    <link rel="stylesheet" href="https://use.typekit.net/emv3zbo.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.digital.arizona.edu/lib/arizona-bootstrap/2.0.18/css/arizona-bootstrap.min.css" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <main>
  <%= render('shared/nav') %>
    
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class='nav'>
<h2 class='item1'><strong><%= link_to '<', root_path %></strong><h2>

<% if current_page?(:controller => 'devise/sessions', :action => 'new') %>
  <%= @title || "LOGIN" %>
<% else %>
  <%= @title || "REGISTER" %>
<% end %>

<h4 class='item3'><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></h4>
</nav>

app/views/splash/index.html.erb
<section>
  <h1>BIGSPENDER</h1>
  <%= link_to('LOG IN', new_user_session_path) %>
  <%= link_to('SIGN UP', new_user_registration_path) %>
</section>